terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while opening the file located at path "./../../../../../library.json": File not found!
